use Kernel#system to codesign extensions in order to avoid error with Rake 11.2.x
If update Rake to 11.2.x,
the codesigning for extensions causes following error

```
$ rake device

    Create ./build/iPhoneOS-9.3-Development/BitWatch.app.dSYM
      Copy ./build/iPhoneOS-9.3-Development/BitWatch.app.dSYM
  Codesign /Users/watson/workspace/BitWatch/build/iPhoneOS-9.3-Development/BitWatch.app/Watch/BitWatch WatchKit App.app/PlugIns/BitWatch WatchKit Extension.appex
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Library/RubyMotion/lib/motion/project/target.rb:133:in `system'
/Library/RubyMotion/lib/motion/project/target/watch_target.rb:52:in `codesign'
/Library/RubyMotion/lib/motion/project/template/ios/builder.rb:71:in `block in codesign'
/Library/RubyMotion/lib/motion/project/template/ios/builder.rb:70:in `each'
/Library/RubyMotion/lib/motion/project/template/ios/builder.rb:70:in `codesign'
/Library/RubyMotion/lib/motion/project/app.rb:86:in `codesign'
/Library/RubyMotion/lib/motion/project/template/ios.rb:76:in `block (2 levels) in <top (required)>'
Tasks: TOP => device => archive => build:device
(See full trace by running task with --trace)
```