build an app even if resources and assets directories does exists
This should fix the following error.
Because, now, android samples does not have resources and assets directories.

$ rake device
   Compile ./app/main_activity.rb
    Create ./build/Development-18/lib/armeabi/libpayload.so
    Create ./build/Development-18/lib/armeabi/gdbserver
    Create ./build/Development-18/lib/armeabi/gdb.setup
    Create ./build/Development-18/AndroidManifest.xml
ERROR: resource directory './resources' does not exist
rake aborted!