fix build error which it was occurred if config.targets is empty
This should fix following error

    NoMethodError: undefined method `empty?' for nil:NilClass
    /Users/watson/prj/RubyMotion/lib/motion/project/builder.rb:238:in `build'
    /Users/watson/prj/RubyMotion/lib/motion/project/app.rb:78:in `build'
    /Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'