fix build error of xassets
By e4495574928c762ec857f948b3efa65a633368ef patch,
the following error has been occurred.

```
$ rake build:simulator
     Build ./build/AppleTVSimulator-10.0-Development
rake aborted!
NoMethodError: undefined method `relative_path' for #<Motion::Project::Builder:0x007ff4bab41d18>
/Library/RubyMotion/lib/motion/project/builder.rb:633:in `compile_asset_bundles'
/Library/RubyMotion/lib/motion/project/builder.rb:411:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion/lib/motion/project/template/tvos.rb:69:in `block (2 levels) in <top (required)>'
```