[OS X 10.11] fix link error of OS X app
Looks like dependent framework is not detected on OS X 10.11.
Maybe, it is related that Xcode 7 does not have the binary of each frameworks.

So far, Security is added with manually to fix link error

```
$ rake
     Build ./build/MacOSX-10.10-Development
   Compile ./app/app_delegate.rb
    Create ./build/MacOSX-10.10-Development/osx.app/Contents
    Create ./build/MacOSX-10.10-Development/osx.app/Contents/MacOS
      Link ./build/MacOSX-10.10-Development/osx.app/Contents/MacOS/osx
Undefined symbols for architecture x86_64:
  "_SecRequirementCreateWithString", referenced from:
      _rb_objc_is_sandboxed in librubymotion-static.a(objc.o)
  "_SecStaticCodeCheckValidityWithErrors", referenced from:
      _rb_objc_is_sandboxed in librubymotion-static.a(objc.o)
  "_SecStaticCodeCreateWithPath", referenced from:
      _rb_objc_is_sandboxed in librubymotion-static.a(objc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
```