Revert "Only load BridgeSupport files for the selected SDK version, instead of all the versions between the deployment target and the SDK version."
This reverts commit 5e90863a56f4ae8bc40db0a952cf97c450f69acb.

Because this patch introduce compile error lile following in test/test

$ rake spec:ios:6.0:32
   TESTING Running test suite on the ios 6.0 SDK with arch 32-bit
    Delete ./build
    Delete vendor/code/build-iPhoneSimulator
    Delete /Users/watson/Library/RubyMotion/build
     Build ./build/iPhoneSimulator-6.0-Development
     Build vendor/code
   Compile vendor/code/blocks.m
   Compile vendor/code/call_ruby.m
   Compile vendor/code/code.m
   Compile vendor/code/special_selectors.m
   Compile /Users/watson/prj/RubyMotion/lib/motion/spec.rb
   Compile /Users/watson/prj/RubyMotion/lib/motion/project/template/ios/spec-helpers/ui.rb
   Compile ./app/app_delegate.rb
   Compile /tmp/deployment_target.rb
   Compile ../../lib/motion/util/version.rb
   Compile ../helpers/bacon.rb
   Compile ../helpers/runloop_yield.rb
   Compile ./spec/alias_spec.rb
^Crake aborted!

rake aborted!

/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:68:in `join'
/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:68:in `block in run'
/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:68:in `each'
/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:68:in `run'
/Users/watson/prj/RubyMotion/lib/motion/project/builder.rb:193:in `build'
/Users/watson/prj/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/watson/prj/RubyMotion/lib/motion/pr/Users/watson/prj/RubyMotion/test/test/Rakefile:126:in `block (7 levels) in <top (required)>'
Tasks: TOP => spec:ios:6.0:32
(See full trace by running task with --trace)
oject/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
/Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:258:in `block (2 levels) in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
[master][~/prj/RubyMotion/test/test]$ rake clean:all
    Delete ./build
    Delete vendor/code/build-iPhoneSimulator
    Delete /Users/watson/Library/RubyMotion/build
[master][~/prj/RubyMotion/test/test]$ rake spec:ios:6.0:32
   TESTING Running test suite on the ios 6.0 SDK with arch 32-bit
    Delete ./build
    Delete /Users/watson/Library/RubyMotion/build
     Build ./build/iPhoneSimulator-6.0-Development
     Build vendor/code
   Compile vendor/code/blocks.m
   Compile vendor/code/call_ruby.m
   Compile vendor/code/code.m
   Compile vendor/code/special_selectors.m
   Compile /Users/watson/prj/RubyMotion/lib/motion/spec.rb
   Compile ../helpers/bacon.rb
   Compile ./app/app_delegate.rb
   Compile /Users/watson/prj/RubyMotion/lib/motion/project/template/ios/spec-helpers/ui.rb
   Compile /tmp/deployment_target.rb
   Compile ./spec/alias_spec.rb
   Compile ../helpers/runloop_yield.rb
   Compile ../../lib/motion/util/version.rb
   Compile ./spec/array_spec.rb
   Compile ./spec/archiver_spec.rb
   Compile ./spec/compile/compile2_spec.rb
   Compile ./spec/cocoa_macro_spec.rb
   Compile ./spec/block_spec.rb
   Compile ./spec/compile/compile4_spec.rb
   Compile ./spec/coremidi_spec.rb
   Compile ./spec/boxed_spec.rb
   Compile ./spec/define_method_spec.rb
   Compile ./spec/exception_spec.rb
   Compile ./spec/compile/compile3_spec.rb
   Compile ./spec/kvo_spec.rb
   Compile ./spec/coredata_spec.rb
   Compile ./spec/delegate_spec.rb
   Compile ./spec/memory_spec.rb
   Compile ./spec/gcd_spec.rb
   Compile ./spec/nsnumber_spec.rb
   Compile ./spec/const_spec.rb
   Compile ./spec/struct_spec.rb
   Compile ./spec/main_spec.rb
   Compile ./spec/module_spec.rb
   Compile ./spec/compile/compile1_spec.rb
   Compile ./spec/function_spec.rb
   Compile ./spec/method_spec.rb
   Compile ./spec/cycle_spec.rb
   Compile ./spec/hash_spec.rb
   Compile ./spec/shortcut_spec.rb
   Compile ./spec/remove_method_spec.rb
   Compile ./spec/not_spec.rb
   Compile ./spec/audio_spec.rb
   Compile ./spec/special_selectors_spec.rb
   Compile ./spec/immediateref_spec.rb
   Compile ./spec/compile/compile5_spec.rb
   Compile ./spec/nsdecimal_spec.rb
   Compile ./spec/float_spec.rb
   Compile ./spec/method_missing_spec.rb
   Compile ./spec/string_spec.rb
   Compile ./spec/protocol_spec.rb
   Compile ./spec/pointer_spec.rb
   Compile ./spec/nsvalue_spec.rb
   Compile ./spec/weakref_spec.rb
   Compile ./spec/type_encoding_spec.rb
   Compile ./spec/super_spec.rb
    Create ./build/iPhoneSimulator-6.0-Development/test_spec.app
      Link ./build/iPhoneSimulator-6.0-Development/test_spec.app/test
Undefined symbols for architecture i386:
  "_NSNotFound", referenced from:
      _MREP_B5FA12E8FC4544D2A094259DBF188981 in main_spec.rb.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Users/watson/prj/RubyMotion/lib/motion/project/builder.rb:357:in `build'
/Users/watson/prj/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
/Users/watson/prj/RubyMotion/lib/motion/project/template/ios.rb:258:in `block (2 levels) in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
[master][~/prj/RubyMotion/test/test]$