[llvm-3.7][Android] generate Assembly file instead of bitcode
Because clang 3.6 in NDK r10e cannot recognize with bitcode generated by LLVM 3.7

```
$ rake jobs=1
   Compile ./app/main_activity.rb
error: Invalid type for value
rake aborted!
Command failed with status (1): [/Users/watson/.rubymotion-android/ndk/tool...]
/Users/watson/prj/RubyMotion/lib/motion/project/template/android.rb:238:in `block (3 levels) in <top (required)>'
/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `call'
/Users/watson/prj/RubyMotion/lib/motion/project/paralel_builder.rb:47:in `block (2 levels) in initialize'
Tasks: TOP => build
(See full trace by running task with --trace)
```